# Generated by Django 5.1.3 on 2024-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0003_printfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfile',
            name='client_name',
            field=models.CharField(default='Nom par défaut', max_length=100, verbose_name='Nom du client'),
        ),
        migrations.AddField(
            model_name='printfile',
            name='contact',
            field=models.CharField(default='Ibrahima', max_length=100, verbose_name='Contact du client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printfile',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
