# Generated by Django 5.1.3 on 2024-12-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_printfile_client_name_printfile_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfile',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Nom du client'),
        ),
    ]
