# Generated by Django 5.1.3 on 2024-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0005_alter_printfile_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfile',
            name='dimensions',
            field=models.CharField(max_length=50, verbose_name='Dimensions  (par ex. 30x40 cm )'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom du client'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='paper_type',
            field=models.CharField(max_length=20, verbose_name="type d'impression (par ex. vyle ou bache)"),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='print_type',
            field=models.CharField(max_length=20, verbose_name="Nombres d'examplare(Ex: 10)"),
        ),
    ]
