# Generated by Django 5.1.3 on 2024-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0006_alter_printfile_dimensions_alter_printfile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Numéro de téléphone')),
                ('description', models.TextField(verbose_name='Description des besoins')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
            ],
        ),
    ]
